"""make lote_id not nullable

Revision ID: 24e7077c7d2f
Revises: 0160900b546a
Create Date: 2025-07-17 17:49:48.737287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24e7077c7d2f'
down_revision: Union[str, Sequence[str], None] = '0160900b546a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servico_pesquisa', 'lote_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servico_pesquisa', 'lote_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
