"""make nome_mae nullable

Revision ID: 36b8e7b85372
Revises: 24e7077c7d2f
Create Date: 2025-07-17 17:52:43.563676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36b8e7b85372'
down_revision: Union[str, Sequence[str], None] = '24e7077c7d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pesquisa', 'nome_mae',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pesquisa', 'nome_mae',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
