"""remoove to uf_rg and uf_nascimento

Revision ID: 52c3c284c528
Revises: f13d181daa09
Create Date: 2025-07-17 14:09:42.049759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52c3c284c528'
down_revision: Union[str, Sequence[str], None] = 'f13d181daa09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pesquisa', 'uf_rg')
    op.drop_column('pesquisa', 'uf_nascimento')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pesquisa', sa.Column('uf_nascimento', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.add_column('pesquisa', sa.Column('uf_rg', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
