"""set tipo lote as nullable

Revision ID: 7b248ce5b699
Revises: b1e20e517fc0
Create Date: 2025-07-20 15:31:39.584602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b248ce5b699'
down_revision: Union[str, Sequence[str], None] = 'b1e20e517fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lote', 'tipo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lote', 'tipo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
