"""add lote_id to servico_pesquisa

Revision ID: 94857fce1eab
Revises: ca06d66ec451
Create Date: 2025-07-17 17:44:17.683749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94857fce1eab'
down_revision: Union[str, Sequence[str], None] = 'ca06d66ec451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servico_pesquisa', sa.Column('lote_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'servico_pesquisa', 'lote', ['lote_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servico_pesquisa', type_='foreignkey')
    op.drop_column('servico_pesquisa', 'lote_id')
    # ### end Alembic commands ###
