"""make pesquisa.cpf nullable

Revision ID: 9762dcf99742
Revises: 7b248ce5b699
Create Date: 2025-07-20 15:42:11.196020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9762dcf99742'
down_revision: Union[str, Sequence[str], None] = '7b248ce5b699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pesquisa', 'cpf',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pesquisa', 'cpf',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    # ### end Alembic commands ###
