"""set unique servico_pesquisa_id

Revision ID: b1e20e517fc0
Revises: f84a19d89039
Create Date: 2025-07-20 13:57:23.387297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1e20e517fc0'
down_revision: Union[str, Sequence[str], None] = 'f84a19d89039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pesquisa', ['servico_pesquisa_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pesquisa', type_='unique')
    # ### end Alembic commands ###
