"""using foreign keys to uf_rg and uf_nascimento

Revision ID: cfbbde0ce57e
Revises: 52c3c284c528
Create Date: 2025-07-17 14:09:57.890381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfbbde0ce57e'
down_revision: Union[str, Sequence[str], None] = '52c3c284c528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pesquisa', sa.Column('uf_rg', sa.Integer(), nullable=True))
    op.add_column('pesquisa', sa.Column('uf_nascimento', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pesquisa', 'estado', ['uf_rg'], ['id'])
    op.create_foreign_key(None, 'pesquisa', 'estado', ['uf_nascimento'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pesquisa', type_='foreignkey')
    op.drop_constraint(None, 'pesquisa', type_='foreignkey')
    op.drop_column('pesquisa', 'uf_nascimento')
    op.drop_column('pesquisa', 'uf_rg')
    # ### end Alembic commands ###
