"""create database

Revision ID: f84a19d89039
Revises: 
Create Date: 2025-07-20 10:10:41.490556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f84a19d89039'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('uf')
    )
    op.create_table('funcionario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('web_site',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fornecedor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['estado_id'], ['estado.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('lote',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('prazo', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('prioridade', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servico_pesquisa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('web_site_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('resultado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lote.id'], ),
    sa.ForeignKeyConstraint(['web_site_id'], ['web_site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pesquisa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('servico_pesquisa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('rg', sa.String(), nullable=True),
    sa.Column('uf_rg', sa.Integer(), nullable=True),
    sa.Column('nascimento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uf_nascimento', sa.Integer(), nullable=True),
    sa.Column('nome_mae', sa.String(), nullable=True),
    sa.Column('data_entrada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_conclusao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anexo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['servico_pesquisa_id'], ['servico_pesquisa.id'], ),
    sa.ForeignKeyConstraint(['uf_nascimento'], ['estado.id'], ),
    sa.ForeignKeyConstraint(['uf_rg'], ['estado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lote_pesquisa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('pesquisa_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('conclusao', sa.String(), nullable=True),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_conclusao', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['estado_id'], ['estado.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lote.id'], ),
    sa.ForeignKeyConstraint(['pesquisa_id'], ['pesquisa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lote_pesquisa')
    op.drop_table('pesquisa')
    op.drop_table('servico_pesquisa')
    op.drop_table('lote')
    op.drop_table('fornecedor')
    op.drop_table('web_site')
    op.drop_table('funcionario')
    op.drop_table('estado')
    # ### end Alembic commands ###
